version: '3.8'
services:
  # Local (DEV) build
  komodo-local:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: development
    ports:
      - "3000:80"
    container_name: komodo-dev
    profiles:
      - dev

  # QA build
  komodo-qa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: qa
    ports:
      - "3001:80"
    container_name: komodo-qa
    profiles:
      - qa

  # Production build
  komodo-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
    ports:
      - "3002:80"
    container_name: komodo-prod
    profiles:
      - prod